### POST request to register a new User
POST https://localhost:8443/api/register
Content-Type: application/json

{
  "fullName": "Test User",
  "email": "test.user@example.com",
  "password": "12345678"
}

###